# Generated by Django 3.0.5 on 2020-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EventCreator',
            fields=[
                ('eventName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('team', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('regno', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=8)),
                ('teamID', models.CharField(max_length=5)),
                ('eventName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('regno', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2)),
                ('tackle', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TackleMember',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='tackle/')),
            ],
        ),
        migrations.CreateModel(
            name='TempMember',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Topscores',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=4)),
            ],
        ),
    ]
