# Generated by Django 3.0.5 on 2020-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MathClubVitap', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
