# Generated by Django 3.0.5 on 2020-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathClubVitap', '0003_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('file', models.FileField(upload_to='tackle/')),
            ],
        ),
    ]
