# Generated by Django 3.0.5 on 2020-05-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MathClubVitap', '0005_auto_20200514_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileCSV',
        ),
    ]
