# Generated by Django 3.0.5 on 2020-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathClubVitap', '0006_auto_20200514_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
